### ISSUE TITLE
Support for modifying target

### ISSUE THREAD

**Issue by ayn2op** [F1bonacc1/glippy#1]
Currently, the `UTF8_STRING` is hard-coded as the atom name in the `glippy_linux.go` file. I propose a new method that accepts the atom name (for target atom) as an argument.

**Comment by F1bonacc1** [comment]
@ayn2op that's an interesting proposal.
Can you elaborate a bit about the use case?
Will this be a cross-platform addition?

**Comment by ayn2op** [comment]
I am working on a TUI application that uses the clipboard to copy and paste text; the project uses atotto/clipboard at the moment, but I plan to switch to `glippy` since images are not supported in `atotto/clipboard` and it is quite unmaintained. You can take a look at the following links for more information. Unfortunately, the Darwin implementation uses `cgo` to interact with Cocoa API.

- Windows implementation to read image from clipboard: https://github.com/golang-design/clipboard/blob/main/clipboard_windows.go#L213
- Darwin implementation to read image from clipboard: https://github.com/golang-design/clipboard/blob/main/clipboard_darwin.go#L41

**Comment by F1bonacc1** [comment]
Looks interesting but there are a few things to consider,
1. The basis for `glippy` is also `atotto/clipboard` and it is text oriented.
2. I completely replaced the Linux implementation to avoid installing additional tools.
3. Darwin implementation is same as `atotto/clipboard` and uses an external process :(
4. I like the windows implementation in `golang-desing/clipboard` - no dependencies, no CGO, image support.
